//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeTile
    {
        public int AttributeId { get; set; }
        public Nullable<int> CharacterProfileId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CorestatValueID { get; set; }
        public string CorestatValue { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string CoreStatName { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CharacterProfile CharacterProfile { get; set; }
        public virtual CoreStatValue CoreStatValue1 { get; set; }
    }
}
