//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlobMap
    {
        public string UserId { get; set; }
        public Nullable<int> CharacterProfileId { get; set; }
        public string BlobContainer { get; set; }
        public string BlobName { get; set; }
    
        public virtual CharacterProfile CharacterProfile { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
