//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.CampaignCoreStats = new HashSet<CampaignCoreStat>();
        }
    
        public int CampaignId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public System.DateTime Authored { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Campaign Campaign1 { get; set; }
        public virtual Campaign Campaign2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignCoreStat> CampaignCoreStats { get; set; }
    }
}
