//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignCoreStat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampaignCoreStat()
        {
            this.CharacterCoreStats = new HashSet<CharacterCoreStat>();
        }
    
        public int CampaignCoreStatId { get; set; }
        public int CampaignId { get; set; }
        public int CoreStatTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Formula { get; set; }
        public string Choices { get; set; }
        public System.DateTime Authored { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual CoreStatType CoreStatType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterCoreStat> CharacterCoreStats { get; set; }
    }
}
