//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CharacterItem()
        {
            this.CharacterItemProperties = new HashSet<CharacterItemProperty>();
        }
    
        public int CharacterItemId { get; set; }
        public Nullable<int> CharacterProfileId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ContentId { get; set; }
        public Nullable<System.DateTime> Authored { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterItemProperty> CharacterItemProperties { get; set; }
        public virtual CharacterProfile CharacterProfile { get; set; }
    }
}
