//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterAbilityProperty
    {
        public int Id { get; set; }
        public Nullable<int> CharacterAbilityId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<bool> ISAction { get; set; }
    
        public virtual CharacterAbility CharacterAbility { get; set; }
    }
}
