//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterCoreStat
    {
        public int CharacterCoreStatId { get; set; }
        public int CharacterProfileId { get; set; }
        public string UserId { get; set; }
        public int CampaignCoreStatId { get; set; }
        public string Value { get; set; }
        public System.DateTime Authored { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
    
        public virtual CampaignCoreStat CampaignCoreStat { get; set; }
        public virtual CharacterProfile CharacterProfile { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
