//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreStat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoreStat()
        {
            this.CoreStatValues = new HashSet<CoreStatValue>();
        }
    
        public int CorestatID { get; set; }
        public Nullable<int> RulesetID { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Metadata { get; set; }
        public Nullable<bool> Mandatory { get; set; }
    
        public virtual RuleSet RuleSet { get; set; }
        public virtual RPGSmithType RPGSmithType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoreStatValue> CoreStatValues { get; set; }
    }
}
