//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAbility
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int AbilityId { get; set; }
    
        public virtual RuleSetItemsContent RuleSetItemsContent { get; set; }
        public virtual RuleSetItemsContent RuleSetItemsContent1 { get; set; }
    }
}
