//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public Nullable<int> ContentId { get; set; }
        public Nullable<int> ContentTypeId { get; set; }
        public string value { get; set; }
        public Nullable<bool> IsStatic { get; set; }
    
        public virtual RuleSetItemsContent RuleSetItemsContent { get; set; }
        public virtual RulesetContentType RulesetContentType { get; set; }
    }
}
