//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Layout()
        {
            this.Tabs = new HashSet<Tab>();
        }
    
        public int LayoutId { get; set; }
        public int CharacterProfileId { get; set; }
        public string UserId { get; set; }
        public string LayoutName { get; set; }
        public System.DateTime Authored { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
        public string DeviceName { get; set; }
        public Nullable<bool> IsDeFault { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CharacterProfile CharacterProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab> Tabs { get; set; }
    }
}
