//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPGSmithType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RPGSmithType()
        {
            this.CoreStats = new HashSet<CoreStat>();
            this.RulesetContentTypes = new HashSet<RulesetContentType>();
            this.RulesetProperties = new HashSet<RulesetProperty>();
        }
    
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Authored { get; set; }
        public string Edited { get; set; }
        public string Units { get; set; }
        public string AllowedValues { get; set; }
        public Nullable<bool> IsCoreStat { get; set; }
        public string Description { get; set; }
        public string Examples { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoreStat> CoreStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RulesetContentType> RulesetContentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RulesetProperty> RulesetProperties { get; set; }
    }
}
