//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using RPGSmith.Data.Models;
    
    public partial class RPGSmithContext : DbContext
    {
        public RPGSmithContext()
            : base("name=RPGSmithContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Ability> Abilities { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AttributeTile> AttributeTiles { get; set; }
        public virtual DbSet<BlobMap> BlobMaps { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<CampaignCoreStat> CampaignCoreStats { get; set; }
        public virtual DbSet<CharacterAbility> CharacterAbilities { get; set; }
        public virtual DbSet<CharacterAbilityProperty> CharacterAbilityProperties { get; set; }
        public virtual DbSet<CharacterCoreStat> CharacterCoreStats { get; set; }
        public virtual DbSet<CharacterItemAbility> CharacterItemAbilities { get; set; }
        public virtual DbSet<CharacterItemProperty> CharacterItemProperties { get; set; }
        public virtual DbSet<CharacterItem> CharacterItems { get; set; }
        public virtual DbSet<CharacterItemSpell> CharacterItemSpells { get; set; }
        public virtual DbSet<CharacterProfile> CharacterProfiles { get; set; }
        public virtual DbSet<CharacterSpellProperty> CharacterSpellProperties { get; set; }
        public virtual DbSet<CharacterSpell> CharacterSpells { get; set; }
        public virtual DbSet<CommandTile> CommandTiles { get; set; }
        public virtual DbSet<CoreStat> CoreStats { get; set; }
        public virtual DbSet<CoreStatType> CoreStatTypes { get; set; }
        public virtual DbSet<CoreStatValue> CoreStatValues { get; set; }
        public virtual DbSet<CounterTile> CounterTiles { get; set; }
        public virtual DbSet<ExecuteTile> ExecuteTiles { get; set; }
        public virtual DbSet<ImageTile> ImageTiles { get; set; }
        public virtual DbSet<ItemAbility> ItemAbilities { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemSpell> ItemSpells { get; set; }
        public virtual DbSet<Layout> Layouts { get; set; }
        public virtual DbSet<LinkTile> LinkTiles { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<NoteTile> NoteTiles { get; set; }
        public virtual DbSet<RPGSmithType> RPGSmithTypes { get; set; }
        public virtual DbSet<RuleSet> RuleSets { get; set; }
        public virtual DbSet<RulesetContentType> RulesetContentTypes { get; set; }
        public virtual DbSet<RuleSetItemsContent> RuleSetItemsContents { get; set; }
        public virtual DbSet<RulesetProperty> RulesetProperties { get; set; }
        public virtual DbSet<RulesetPropertyValue> RulesetPropertyValues { get; set; }
        public virtual DbSet<Spell> Spells { get; set; }
        public virtual DbSet<Tab> Tabs { get; set; }
        public virtual DbSet<Tile> Tiles { get; set; }
        public virtual DbSet<TileLocation> TileLocations { get; set; }
        public virtual DbSet<TileType> TileTypes { get; set; }
        public virtual DbSet<UserAccountSetting> UserAccountSettings { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserVirtualDice> UserVirtualDices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleClaim> RoleClaims { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserToken> UserTokens { get; set; }
        public virtual DbSet<bkp_CharacterItemSpells> bkp_CharacterItemSpells { get; set; }
        public virtual DbSet<bkp_ItemSpell> bkp_ItemSpell { get; set; }
        public virtual DbSet<characterprofile_BCK_15092017> characterprofile_BCK_15092017 { get; set; }
        public virtual DbSet<Counter_BCK_26092017> Counter_BCK_26092017 { get; set; }
        public virtual DbSet<Layout_BCK_26092017> Layout_BCK_26092017 { get; set; }
        public virtual DbSet<Note_BCK_26092017> Note_BCK_26092017 { get; set; }
        public virtual DbSet<NoteTile_30102017> NoteTile_30102017 { get; set; }
        public virtual DbSet<RPGSmithType_BCK_08092014> RPGSmithType_BCK_08092014 { get; set; }
        public virtual DbSet<Tab_BCK_26092017> Tab_BCK_26092017 { get; set; }
        public virtual DbSet<Temp_Bak> Temp_Bak { get; set; }
        public virtual DbSet<Tile_BCK_26092017> Tile_BCK_26092017 { get; set; }
        public virtual DbSet<TileType_BCK_26092017> TileType_BCK_26092017 { get; set; }
    }
}
