//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPGSmithType_BCK_08092014
    {
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Authored { get; set; }
        public string Edited { get; set; }
        public string Units { get; set; }
        public string AllowedValues { get; set; }
    }
}
