//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RuleSet()
        {
            this.CoreStats = new HashSet<CoreStat>();
            this.RuleSetItemsContents = new HashSet<RuleSetItemsContent>();
            this.RulesetPropertyValues = new HashSet<RulesetPropertyValue>();
        }
    
        public int RulesetID { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public System.DateTime Authored { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoreStat> CoreStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSetItemsContent> RuleSetItemsContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RulesetPropertyValue> RulesetPropertyValues { get; set; }
    }
}
