//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulesetProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RulesetProperty()
        {
            this.RulesetPropertyValues = new HashSet<RulesetPropertyValue>();
        }
    
        public int PropertyId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual RPGSmithType RPGSmithType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RulesetPropertyValue> RulesetPropertyValues { get; set; }
    }
}
