//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulesetContentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RulesetContentType()
        {
            this.Abilities = new HashSet<Ability>();
            this.Items = new HashSet<Item>();
            this.Spells = new HashSet<Spell>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ContentType { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Metadata { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsRuleSet { get; set; }
        public Nullable<bool> IsFormula { get; set; }
        public string Formula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ability> Abilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        public virtual RPGSmithType RPGSmithType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spell> Spells { get; set; }
    }
}
