//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_BCK_26092017
    {
        public int TabId { get; set; }
        public int LayoutId { get; set; }
        public int UserId { get; set; }
        public string TabName { get; set; }
        public short TabOrder { get; set; }
        public System.DateTime Authored { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
    }
}
