//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Bak
    {
        public int Id { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public string Value { get; set; }
        public Nullable<int> RulesetID { get; set; }
    }
}
