//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tile
    {
        public long TileId { get; set; }
        public int TileContentId { get; set; }
        public string UserId { get; set; }
        public int TileTypeId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string Style { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public System.DateTime Authored { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
        public Nullable<int> TileLocationId { get; set; }
        public Nullable<bool> IsEditable { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual TileLocation TileLocation { get; set; }
        public virtual TileType TileType { get; set; }
    }
}
