//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGSmith.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountSetting
    {
        public string UserID { get; set; }
        public Nullable<bool> ShowVirtualDice { get; set; }
        public int Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
